
// This file was automatically generated by gen_gallery.py & should not be
// modified directly.

images = new Array();

images[0] = ['examples/General/thumbnails/SOI_filtering.png', '_images/SOI_filtering.png', 'examples/General/SOI_filtering.html#SOI-filtering'];
images[1] = ['examples/General/thumbnails/anomaly_log_colouring.png', '_images/anomaly_log_colouring.png', 'examples/General/anomaly_log_colouring.html#anomaly-log-colouring'];
images[2] = ['examples/General/thumbnails/coriolis_plot_01_00.png', '_images/coriolis_plot_01_00.png', 'examples/General/coriolis_plot.html#coriolis-plot-01-00'];
images[3] = ['examples/General/thumbnails/cross_section_00.png', '_images/cross_section_00.png', 'examples/General/cross_section.html#cross-section-00'];
images[4] = ['examples/General/thumbnails/cross_section_01.png', '_images/cross_section_01.png', 'examples/General/cross_section.html#cross-section-01'];
images[5] = ['examples/General/thumbnails/custom_aggregation.png', '_images/custom_aggregation.png', 'examples/General/custom_aggregation.html#custom-aggregation'];
images[6] = ['examples/General/thumbnails/custom_file_loading.png', '_images/custom_file_loading.png', 'examples/General/custom_file_loading.html#custom-file-loading'];
images[7] = ['examples/General/thumbnails/inset_plot.png', '_images/inset_plot.png', 'examples/General/inset_plot.html#inset-plot'];
images[8] = ['examples/General/thumbnails/orca_projection_00.png', '_images/orca_projection_00.png', 'examples/General/orca_projection.html#orca-projection-00'];
images[9] = ['examples/General/thumbnails/orca_projection_01.png', '_images/orca_projection_01.png', 'examples/General/orca_projection.html#orca-projection-01'];
images[10] = ['examples/General/thumbnails/orca_projection_02.png', '_images/orca_projection_02.png', 'examples/General/orca_projection.html#orca-projection-02'];
images[11] = ['examples/General/thumbnails/orca_projection_03.png', '_images/orca_projection_03.png', 'examples/General/orca_projection.html#orca-projection-03'];
images[12] = ['examples/General/thumbnails/polynomial_fit.png', '_images/polynomial_fit.png', 'examples/General/polynomial_fit.html#polynomial-fit'];
images[13] = ['examples/General/thumbnails/projections_and_annotations_00.png', '_images/projections_and_annotations_00.png', 'examples/General/projections_and_annotations.html#projections-and-annotations-00'];
images[14] = ['examples/General/thumbnails/projections_and_annotations_01.png', '_images/projections_and_annotations_01.png', 'examples/General/projections_and_annotations.html#projections-and-annotations-01'];
images[15] = ['examples/General/thumbnails/rotated_pole_mapping_00.png', '_images/rotated_pole_mapping_00.png', 'examples/General/rotated_pole_mapping.html#rotated-pole-mapping-00'];
images[16] = ['examples/General/thumbnails/rotated_pole_mapping_01.png', '_images/rotated_pole_mapping_01.png', 'examples/General/rotated_pole_mapping.html#rotated-pole-mapping-01'];
images[17] = ['examples/General/thumbnails/rotated_pole_mapping_02.png', '_images/rotated_pole_mapping_02.png', 'examples/General/rotated_pole_mapping.html#rotated-pole-mapping-02'];
images[18] = ['examples/General/thumbnails/rotated_pole_mapping_03.png', '_images/rotated_pole_mapping_03.png', 'examples/General/rotated_pole_mapping.html#rotated-pole-mapping-03'];
images[19] = ['examples/Meteorology/thumbnails/TEC.png', '_images/TEC.png', 'examples/Meteorology/TEC.html#TEC'];
images[20] = ['examples/Meteorology/thumbnails/hovmoller.png', '_images/hovmoller.png', 'examples/Meteorology/hovmoller.html#hovmoller'];
images[21] = ['examples/Oceanography/thumbnails/atlantic_profiles_00.png', '_images/atlantic_profiles_00.png', 'examples/Oceanography/atlantic_profiles.html#atlantic-profiles-00'];
images[22] = ['examples/Oceanography/thumbnails/atlantic_profiles_01.png', '_images/atlantic_profiles_01.png', 'examples/Oceanography/atlantic_profiles.html#atlantic-profiles-01'];

