
// This file was automatically generated by gen_gallery.py & should not be
// modified directly.

images = new Array();

images[0] = ['examples/General/thumbnails/SOI_filtering.png', '_images/SOI_filtering.png', 'examples/General/SOI_filtering.html#SOI-filtering'];
images[1] = ['examples/General/thumbnails/cross_section_00.png', '_images/cross_section_00.png', 'examples/General/cross_section.html#cross-section-00'];
images[2] = ['examples/General/thumbnails/cross_section_01.png', '_images/cross_section_01.png', 'examples/General/cross_section.html#cross-section-01'];
images[3] = ['examples/General/thumbnails/custom_aggregation.png', '_images/custom_aggregation.png', 'examples/General/custom_aggregation.html#custom-aggregation'];
images[4] = ['examples/General/thumbnails/custom_file_loading.png', '_images/custom_file_loading.png', 'examples/General/custom_file_loading.html#custom-file-loading'];
images[5] = ['examples/General/thumbnails/global_map.png', '_images/global_map.png', 'examples/General/global_map.html#global-map'];
images[6] = ['examples/General/thumbnails/lineplot_with_legend.png', '_images/lineplot_with_legend.png', 'examples/General/lineplot_with_legend.html#lineplot-with-legend'];
images[7] = ['examples/General/thumbnails/polar_stereo.png', '_images/polar_stereo.png', 'examples/General/polar_stereo.html#polar-stereo'];
images[8] = ['examples/General/thumbnails/polynomial_fit.png', '_images/polynomial_fit.png', 'examples/General/polynomial_fit.html#polynomial-fit'];
images[9] = ['examples/Meteorology/thumbnails/COP_1d_plot.png', '_images/COP_1d_plot.png', 'examples/Meteorology/COP_1d_plot.html#COP-1d-plot'];
images[10] = ['examples/Meteorology/thumbnails/COP_maps.png', '_images/COP_maps.png', 'examples/Meteorology/COP_maps.html#COP-maps'];
images[11] = ['examples/Meteorology/thumbnails/TEC.png', '_images/TEC.png', 'examples/Meteorology/TEC.html#TEC'];
images[12] = ['examples/Meteorology/thumbnails/deriving_phenomena.png', '_images/deriving_phenomena.png', 'examples/Meteorology/deriving_phenomena.html#deriving-phenomena'];
images[13] = ['examples/Meteorology/thumbnails/hovmoller.png', '_images/hovmoller.png', 'examples/Meteorology/hovmoller.html#hovmoller'];
images[14] = ['examples/Meteorology/thumbnails/lagged_ensemble_00.png', '_images/lagged_ensemble_00.png', 'examples/Meteorology/lagged_ensemble.html#lagged-ensemble-00'];
images[15] = ['examples/Meteorology/thumbnails/lagged_ensemble_01.png', '_images/lagged_ensemble_01.png', 'examples/Meteorology/lagged_ensemble.html#lagged-ensemble-01'];
images[16] = ['examples/Meteorology/thumbnails/wind_speed_00.png', '_images/wind_speed_00.png', 'examples/Meteorology/wind_speed.html#wind-speed-00'];
images[17] = ['examples/Meteorology/thumbnails/wind_speed_01.png', '_images/wind_speed_01.png', 'examples/Meteorology/wind_speed.html#wind-speed-01'];
images[18] = ['examples/Oceanography/thumbnails/atlantic_profiles_00.png', '_images/atlantic_profiles_00.png', 'examples/Oceanography/atlantic_profiles.html#atlantic-profiles-00'];
images[19] = ['examples/Oceanography/thumbnails/atlantic_profiles_01.png', '_images/atlantic_profiles_01.png', 'examples/Oceanography/atlantic_profiles.html#atlantic-profiles-01'];
images[20] = ['examples/Oceanography/thumbnails/load_nemo.png', '_images/load_nemo.png', 'examples/Oceanography/load_nemo.html#load-nemo'];

